#include "cir_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <wchar.h>
#include <ctype.h>
#include <setjmp.h>
#include <dlfcn.h>

#define xstr(s) str(s)
#define str(s) #s
#define SYM(name) { xstr(name), &name }

static struct {
    const char *name;
    void *ptr;
} builtinsymbols[] = {

// CIR API
    SYM(CirLog_begin),
    SYM(CirLog_print),
    SYM(CirLog_printb),
    SYM(CirLog_printf),
    SYM(CirLog_vprintf),
    SYM(CirLog_printq),
    SYM(CirLog_printqb),
    SYM(CirLog_end),
    SYM(cir_fatal),
    SYM(cir_bug),
    SYM(cir_warn),
    SYM(cir_log),
    SYM(CirPrime_ge),
    SYM(CirMem_balloc),
    SYM(CirMachine_getBuild),
    SYM(CirMachine_getHost),
    SYM(CirIkind_size),
    SYM(CirIkind_isSigned),
    SYM(CirIkind_toUnsigned),
    SYM(CirIkind_fromSize),
    SYM(CirFkind_size),
    SYM(CirFkind_fromSize),
    SYM(CirName_of),
    SYM(CirName_cstr),
    SYM(CirName_log),
    SYM(CirAttr_int),
    SYM(CirAttr_str),
    SYM(CirAttr_name),
    SYM(CirAttr_cons),
    SYM(CirAttr_isInt),
    SYM(CirAttr_isStr),
    SYM(CirAttr_isName),
    SYM(CirAttr_isCons),
    SYM(CirAttr_getName),
    SYM(CirAttr_getNumArgs),
    SYM(CirAttr_getArgs),
    SYM(CirAttr_log),
    SYM(CirType_isVoid),
    SYM(CirType_isInt),
    SYM(CirType_isFloat),
    SYM(CirType_isArithmetic),
    SYM(CirType_isPtr),
    SYM(CirType_isArray),
    SYM(CirType_isFun),
    SYM(CirType_isNamed),
    SYM(CirType_isComp),
    SYM(CirType_isEnum),
    SYM(CirType_isVaList),
    SYM(CirType_getBaseType),
    SYM(CirType_getTypedefId),
    SYM(CirType_getCompId),
    SYM(CirType_getEnumId),
    SYM(CirType_void),
    SYM(CirType_int),
    SYM(CirType_float),
    SYM(CirType_typedef),
    SYM(CirType_comp),
    SYM(CirType_enum),
    SYM(CirType_ptr),
    SYM(CirType_array),
    SYM(CirType_arrayWithLen),
    SYM(CirType_fun),
    SYM(CirType_valist),
    SYM(CirType_unroll),
    SYM(CirType_unrollDeep),
    SYM(CirType_removeQual),
    SYM(CirType_lvalConv),
    SYM(CirType_getNumAttrs),
    SYM(CirType_getAttrs),
    SYM(CirType_withAttrs),
    SYM(CirType_replaceAttrs),
    SYM(CirType_removeAttrs),
    SYM(CirType_getNumParams),
    SYM(CirType_getParams),
    SYM(CirType_isParamsVa),
    SYM(CirType_hasArrayLen),
    SYM(CirType_getArrayLen),
    SYM(CirType_alignof),
    SYM(CirType_sizeof),
    SYM(CirType_log),
    SYM(CirType_equals),
    SYM(CirBuiltin_ofName),
    SYM(CirBuiltin_getName),
    SYM(CirBuiltin_getType),
    SYM(CirVar_new),
    SYM(CirVar_getName),
    SYM(CirVar_setName),
    SYM(CirVar_getType),
    SYM(CirVar_setType),
    SYM(CirVar_getFormal),
    SYM(CirVar_setFormal),
    SYM(CirVar_getCode),
    SYM(CirVar_setCode),
    SYM(CirVar_getOwner),
    SYM(CirVar_getStorage),
    SYM(CirVar_setStorage),
    SYM(CirVar_log),
    SYM(CirVar_logNameAndType),
    SYM(CirTypedef_new),
    SYM(CirTypedef_getName),
    SYM(CirTypedef_getType),
    SYM(CirTypedef_log),
    SYM(CirComp_new),
    SYM(CirComp_isStruct),
    SYM(CirComp_setStruct),
    SYM(CirComp_isDefined),
    SYM(CirComp_setDefined),
    SYM(CirComp_getName),
    SYM(CirComp_setName),
    SYM(CirComp_getNumFields),
    SYM(CirComp_setNumFields),
    SYM(CirComp_getFieldName),
    SYM(CirComp_setFieldName),
    SYM(CirComp_getFieldType),
    SYM(CirComp_setFieldType),
    SYM(CirComp_hasFieldBitsize),
    SYM(CirComp_getFieldBitsize),
    SYM(CirComp_setFieldBitsize),
    SYM(CirComp_clearFieldBitsize),
    SYM(CirComp_getFieldByName),
    SYM(CirComp_getFieldAlign),
    SYM(CirComp_getAlign),
    SYM(CirComp_getSize),
    SYM(CirComp_getFieldBitsOffset),
    SYM(CirComp_log),
    SYM(CirEnum_new),
    SYM(CirEnum_getName),
    SYM(CirEnum_setName),
    SYM(CirEnum_getNumItems),
    SYM(CirEnum_setNumItems),
    SYM(CirEnum_getItem),
    SYM(CirEnum_setItem),
    SYM(CirEnum_getIkind),
    SYM(CirEnum_setIkind),
    SYM(CirEnum_isDefined),
    SYM(CirEnum_setDefined),
    SYM(CirEnumItem_new),
    SYM(CirEnumItem_getName),
    SYM(CirEnumItem_getI64),
    SYM(CirEnumItem_setI64),
    SYM(CirValue_registerUser),
    SYM(CirValue_ofU64),
    SYM(CirValue_ofI64),
    SYM(CirValue_ofVar),
    SYM(CirValue_ofMem),
    SYM(CirValue_ofUser),
    SYM(CirValue_ofString),
    SYM(CirValue_ofCString),
    SYM(CirValue_ofType),
    SYM(CirValue_ofBuiltin),
    SYM(CirValue_isInt),
    SYM(CirValue_isString),
    SYM(CirValue_isVar),
    SYM(CirValue_isMem),
    SYM(CirValue_isLval),
    SYM(CirValue_isUser),
    SYM(CirValue_isType),
    SYM(CirValue_isBuiltin),
    SYM(CirValue_getU64),
    SYM(CirValue_getI64),
    SYM(CirValue_getString),
    SYM(CirValue_getNumFields),
    SYM(CirValue_getField),
    SYM(CirValue_withFields),
    SYM(CirValue_getVar),
    SYM(CirValue_withVar),
    SYM(CirValue_getPtr),
    SYM(CirValue_getType),
    SYM(CirValue_getRawType),
    SYM(CirValue_getCastType),
    SYM(CirValue_withCastType),
    SYM(CirValue_getTypeValue),
    SYM(CirValue_log),
    SYM(CirStmt_registerUser),
    SYM(CirStmt_newOrphan),
    SYM(CirStmt_newAfter),
    SYM(CirStmt_newBefore),
    SYM(CirStmt_orphanize),
    SYM(CirStmt_isOrphan),
    SYM(CirStmt_toNop),
    SYM(CirStmt_toUnOp),
    SYM(CirStmt_toBinOp),
    SYM(CirStmt_toCall),
    SYM(CirStmt_toReturn),
    SYM(CirStmt_toCmp),
    SYM(CirStmt_toGoto),
    SYM(CirStmt_toLabel),
    SYM(CirStmt_toGotoLabel),
    SYM(CirStmt_toUser),
    SYM(CirStmt_isNop),
    SYM(CirStmt_isUnOp),
    SYM(CirStmt_isBinOp),
    SYM(CirStmt_isCall),
    SYM(CirStmt_isReturn),
    SYM(CirStmt_isCmp),
    SYM(CirStmt_isGoto),
    SYM(CirStmt_isJump),
    SYM(CirStmt_isLabel),
    SYM(CirStmt_isGotoLabel),
    SYM(CirStmt_isUser),
    SYM(CirStmt_getOp),
    SYM(CirStmt_getDst),
    SYM(CirStmt_getOperand1),
    SYM(CirStmt_getOperand2),
    SYM(CirStmt_getNumOperands),
    SYM(CirStmt_getOperand),
    SYM(CirStmt_setOperand),
    SYM(CirStmt_getNumArgs),
    SYM(CirStmt_getArg),
    SYM(CirStmt_getJumpTarget),
    SYM(CirStmt_setJumpTarget),
    SYM(CirStmt_getLabelName),
    SYM(CirStmt_setLabelName),
    SYM(CirStmt_getPtr),
    SYM(CirStmt_setPtr),
    SYM(CirStmt_getNext),
    SYM(CirStmt_getPrev),
    SYM(CirStmt_log),
    SYM(CirStmt_typecheck),
    SYM(CirCode_ofExpr),
    SYM(CirCode_ofCond),
    SYM(CirCode_appendNewStmt),
    SYM(CirCode_prependNewStmt),
    SYM(CirCode_appendOrphanStmt),
    SYM(CirCode_isExpr),
    SYM(CirCode_isCond),
    SYM(CirCode_free),
    SYM(CirCode_getValue),
    SYM(CirCode_setValue),
    SYM(CirCode_getFirstStmt),
    SYM(CirCode_getLastStmt),
    SYM(CirCode_addTrueJump),
    SYM(CirCode_addFalseJump),
    SYM(CirCode_toExpr),
    SYM(CirCode_getType),
    SYM(CirCode_append),
    SYM(CirCode_dump),
    SYM(CirCode_getNumVars),
    SYM(CirCode_getVar),
    SYM(CirCode_typecheck),
    SYM(CirCode_resolveLabels),

// C library
    // https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rtref/stalib.htm

    SYM(abort),
    SYM(abs),
    SYM(asctime),
    SYM(atexit),
    SYM(atof),
    SYM(atoi),
    SYM(atol),
    SYM(bsearch),
    SYM(btowc),
    SYM(calloc),
    SYM(clearerr),
    SYM(clock),
    SYM(ctime),
    SYM(difftime),
    SYM(div),
    SYM(exit),
    SYM(fclose),
    SYM(feof),
    SYM(ferror),
    SYM(fflush),
    SYM(fgetc),
    SYM(fgetpos),
    SYM(fgets),
    SYM(fgetwc),
    SYM(fopen),
    SYM(fprintf),
    SYM(fputc),
    SYM(fputs),
    SYM(fputwc),
    SYM(fputws),
    SYM(fread),
    SYM(free),
    SYM(freopen),
    SYM(frexp),
    SYM(fscanf),
    SYM(fseek),
    SYM(fsetpos),
    SYM(ftell),
    SYM(fwide),
    SYM(fwprintf),
    SYM(fwrite),
    SYM(fwscanf),
    SYM(getc),
    SYM(getchar),
    SYM(getenv),
    SYM(getwc),
    SYM(getwchar),
    SYM(gmtime),
    SYM(isalnum),
    SYM(isalpha),
    SYM(iscntrl),
    SYM(isdigit),
    SYM(isgraph),
    SYM(islower),
    SYM(isprint),
    SYM(ispunct),
    SYM(isspace),
    SYM(isupper),
    SYM(labs),
    SYM(ldexp),
    SYM(ldiv),
    SYM(localtime),
    SYM(malloc),
    SYM(mblen),
    SYM(memchr),
    SYM(memcmp),
    SYM(memcpy),
    SYM(memmove),
    SYM(memset),
    SYM(mktime),
    SYM(modf),
    SYM(printf),
    SYM(putc),
    SYM(putchar),
    SYM(puts),
    SYM(qsort),
    SYM(rand),
    SYM(realloc),
    SYM(snprintf),
    SYM(sprintf),
    SYM(srand),
    SYM(sscanf),
    SYM(strcat),
    SYM(strchr),
    SYM(strcmp),
    SYM(strcpy),
    SYM(strcspn),
    SYM(strerror),
    SYM(strftime),
    SYM(strlen),
    SYM(strncat),
    SYM(strncmp),
    SYM(strncpy),
    SYM(strpbrk),
    SYM(strrchr),
    SYM(strspn),
    SYM(strstr),
    SYM(strtod),
    SYM(strtof),
    SYM(strtok),
    SYM(strtol),
    SYM(strtold),
    SYM(strtoul),
    SYM(strxfrm),
    SYM(swprintf),
    SYM(swscanf),
    SYM(system),
    SYM(time),
    SYM(tmpfile),
    SYM(tolower),
    SYM(toupper),
    SYM(vfprintf),
    SYM(vfscanf),
    SYM(vprintf),
    SYM(vscanf),
    SYM(vsprintf),
    SYM(vsnprintf),
    SYM(vsscanf),
    SYM(vswprintf),
    SYM(stdin),
    SYM(stdout),
    SYM(stderr),

// end
    {}
};

static CirArray(void *) loadedLibraries;

void
CirDl_loadLibrary(const char *filename)
{
    void *handle = dlopen(filename, RTLD_LAZY | RTLD_LOCAL);
    if (!handle)
        cir_fatal("failed to load library: %s", filename);
    CirArray_push(&loadedLibraries, &handle);
}

bool
CirDl_findSymbol(const char *name, void **out)
{
    for (size_t i = 0; builtinsymbols[i].name; i++) {
        if (!strcmp(builtinsymbols[i].name, name)) {
            *out = builtinsymbols[i].ptr;
            return true;
        }
    }

    for (size_t i = 0; i < loadedLibraries.len; i++) {
        dlerror(); // clear dlerror
        void *ptr = dlsym(loadedLibraries.items[i], name);
        const char *err = dlerror();
        if (err)
            continue;
        *out = ptr;
        return true;
    }

    return false;
}
